name: Auto-Discover and Distribute Nexus Secrets

on:
  schedule:
    # Run every 5 days to keep cookies fresh
    - cron: "0 0 */5 * *"
  workflow_dispatch:
    inputs:
      force_update:
        description: "Force update even if Nexus cookie refresh fails"
        type: boolean
        default: false
        required: false
      dry_run:
        description: "Test discovery without updating secrets"
        type: boolean
        default: false
        required: false

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  discover-and-distribute:
    name: Discover and Distribute
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup UNEX
        uses: ./.github/actions/setup-unex

      - name: Refresh Nexus session cookie
        id: refresh
        uses: ./.github/actions/refresh-nexus
        with:
          nexus-session-cookie: ${{ secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
        continue-on-error: true

      - name: Discover repositories using Nexus uploads
        id: discover
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          Write-Output "----------------------------------------"
          Write-Output "[INFO] Discovering repositories with Nexus uploads"
          Write-Output "----------------------------------------"

          # Mask the token
          Write-Output "::add-mask::$env:GH_TOKEN"

          ./scripts/discover-repos.ps1 `
             -SearchQueries "UNEX_NEXUSMODS_SESSION_COOKIE,NexusUploader,nexus-workflows" `
             -IncludeRepos "${{ vars.UNEX_INCLUDE_REPOS || secrets.UNEX_INCLUDE_REPOS }}" `
             -ExcludeRepos "${{ vars.UNEX_EXCLUDE_REPOS || secrets.UNEX_EXCLUDE_REPOS }}" `
             -CurrentRepo "${{ github.repository }}" `
             -Owner "${{ github.repository_owner }}" `
             > repos.json

          # Read back json safely
          $reposJson = Get-Content repos.json -Raw
          $repos = $reposJson | ConvertFrom-Json
          $count = if ($repos) { $repos.Count } else { 0 }

          Write-Output "[INFO] Total repositories found: $count"

          Write-Output "REPOS=$reposJson" >> $env:GITHUB_OUTPUT
          Write-Output "REPO_COUNT=$count" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Distribute secrets to discovered repos
        if: |
          (steps.refresh.outputs.REFRESHED == 'true' || inputs.force_update) &&
          !inputs.dry_run && steps.discover.outputs.REPO_COUNT > 0
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
          COOKIE: ${{ steps.refresh.outputs.new-cookie || secrets.UNEX_NEXUSMODS_SESSION_COOKIE }}
          APIKEY: ${{ secrets.UNEX_APIKEY }}
          REPOS_JSON: ${{ steps.discover.outputs.REPOS }}
          EXCLUDE_REPOS: ${{ vars.UNEX_EXCLUDE_REPOS || secrets.UNEX_EXCLUDE_REPOS }}
        run: |
          # Ensure sensitive env vars are masked
          Write-Output "::add-mask::$env:GH_TOKEN"
          Write-Output "::add-mask::$env:COOKIE"
          if ($env:APIKEY) { Write-Output "::add-mask::$env:APIKEY" }

          ./scripts/distribute-secrets.ps1 `
            -ReposJson $env:REPOS_JSON `
            -Cookie $env:COOKIE `
            -ApiKey $env:APIKEY `
            -ExcludeRepos $env:EXCLUDE_REPOS
        shell: pwsh

      - name: Dry run summary
        if: inputs.dry_run
        env:
          REPOS_JSON: ${{ steps.discover.outputs.REPOS }}
          EXCLUDE_REPOS: ${{ vars.UNEX_EXCLUDE_REPOS || secrets.UNEX_EXCLUDE_REPOS }}
        run: |
          ./scripts/distribute-secrets.ps1 `
            -ReposJson $env:REPOS_JSON `
            -ExcludeRepos $env:EXCLUDE_REPOS `
            -DryRun
        shell: pwsh

      - name: Report status
        if: always()
        env:
          REFRESHED: ${{ steps.refresh.outputs.REFRESHED }}
          REPO_COUNT: ${{ steps.discover.outputs.REPO_COUNT }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          if ($env:DRY_RUN -eq 'true') {
            Write-Output "::notice::[TEST] Dry run completed - discovered $env:REPO_COUNT repositories"
          } elseif ($env:REFRESHED -eq 'true') {
            Write-Output "::notice::[SUCCESS] Cookie refreshed and distributed to $env:REPO_COUNT repositories"
          } else {
            Write-Output "::error::[ERROR] Cookie refresh failed - manual update required!"
            Write-Output "::error::Please update UNEX_NEXUSMODS_SESSION_COOKIE secret and re-run this workflow"
          }
        shell: pwsh

      - name: Cookie refresh failure notice
        if: failure() && steps.refresh.outputs.REFRESHED == 'false'
        run: |
          Write-Output "::error::=========================================="
          Write-Output "::error::NEXUS SESSION COOKIE EXPIRED"
          Write-Output "::error::=========================================="
          Write-Output "::error::"
          Write-Output "::error::Your stored cookie is too old to refresh automatically."
          Write-Output "::error::"
          Write-Output "::error::ACTION REQUIRED:"
          Write-Output "::error::  1. Go to https://www.nexusmods.com and log in"
          Write-Output "::error::  2. Press F12 -> Application/Storage -> Cookies"
          Write-Output "::error::  3. Copy the value of 'nexusmods_session'"
          Write-Output "::error::  4. Update at: your repository settings/secrets/actions"
          Write-Output "::error::  5. Update the UNEX_NEXUSMODS_SESSION_COOKIE secret"
          Write-Output "::error::  6. Re-run this workflow to distribute to all mods"
          Write-Output "::error::"
          Write-Output "::error::=========================================="
        shell: pwsh
